version: '3.5'

services:
  db_cities:
    container_name: db_cities
    ports:
      - "8082:5432"
    environment:
      - POSTGRES_PASSWORD=1p3p5p7p
      - POSTGRES_USER=admin
    image: postgres:14.4-alpine
  app_cities:
    container_name: app_cities
    build:
      context: ./
      dockerfile: Dockerfile
    image: cities-shower:1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_cities:5432/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1p3p5p7p
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.yml
    ports:
      - "8083:8080"
    links:
      - db_cities
    depends_on:
      - db_cities