version: '3.5'

services:
  db_cities:
    container_name: db_cities
    ports:
      - "8082:5432"
    environment:
      - POSTGRES_PASSWORD=1p3p5p7p
      - POSTGRES_USER=admin
    image: postgres:14.4-alpine